package Threads;

public class Printer implements Runnable {
private String text;
public Printer(String text) {
	this.text= text;
}


public String getText() {
	return text;
}

public void setText(String text) {
	this.text = text;
}


@Override
public void run() {
	// TODO Auto-generated method stub
	System.out.println(text+"this is generated by"+Thread.currentThread().getName());
	
}
}
